/**
 * Construit l'URL GitHub Issues préremplie à partir du contexte feedback.
 *
 * Pratique : URLs GitHub Issues fonctionnent jusqu'à ~8000 chars en pratique.
 * On vise un body ≤ 7000 chars avec **troncature progressive** :
 *   1. Erreurs console (la plus volatile)
 *   2. Filtres actifs
 *   3. Description (en dernier recours)
 * On annote `…[truncated]` à chaque section tronquée.
 */
import type { Classification, FeedbackType } from './classifyFeedback'
import type { FeedbackContext } from './collectContext'

const REPO = 'JGtm/LevelUp'
const BASE_URL = `https://github.com/${REPO}/issues/new`
const MAX_BODY_LENGTH = 7000
const TRUNCATED_MARKER = '…[truncated]'

const TYPE_LABEL_MAP: Record<FeedbackType, string> = {
  bug: 'bug',
  enhancement: 'enhancement',
  question: 'question',
}

const TYPE_PREFIX_MAP: Record<FeedbackType, string> = {
  bug: '[Bug] ',
  enhancement: '[Idea] ',
  question: '[?] ',
}

export interface BuildIssueUrlInput {
  title: string
  description: string
  context: FeedbackContext
  classification: Classification
}

export interface BuildIssueUrlResult {
  url: string
  body: string
  wasTruncated: boolean
}

export function buildIssueUrl(input: BuildIssueUrlInput): BuildIssueUrlResult {
  const fullTitle = TYPE_PREFIX_MAP[input.classification.type] + input.title
  const labels = [
    'feedback',
    TYPE_LABEL_MAP[input.classification.type],
    `severity:${input.classification.severity}`,
    `area:${input.classification.area}`,
  ].join(',')

  const { body, wasTruncated } = buildBody(input)
  const params = new URLSearchParams({
    labels,
    title: fullTitle,
    body,
  })
  return { url: `${BASE_URL}?${params.toString()}`, body, wasTruncated }
}

interface BodySections {
  description: string
  context: string
  environment: string
  filters: string
  classification: string
  consoleErrors: string
  failedRequests: string
  footer: string
}

function buildBody(input: BuildIssueUrlInput): { body: string; wasTruncated: boolean } {
  const sections = renderSections(input)
  let body = composeBody(sections)

  if (body.length <= MAX_BODY_LENGTH) return { body, wasTruncated: false }

  // Troncature progressive : erreurs console → filtres → description
  sections.consoleErrors = TRUNCATED_MARKER
  sections.failedRequests = TRUNCATED_MARKER
  body = composeBody(sections)

  if (body.length > MAX_BODY_LENGTH) {
    sections.filters = TRUNCATED_MARKER
    body = composeBody(sections)
  }
  if (body.length > MAX_BODY_LENGTH) {
    const remaining = MAX_BODY_LENGTH - (body.length - sections.description.length)
    const safeBudget = Math.max(200, remaining - TRUNCATED_MARKER.length - 4)
    sections.description = sections.description.slice(0, safeBudget) + '\n' + TRUNCATED_MARKER
    body = composeBody(sections)
  }
  return { body, wasTruncated: true }
}

function composeBody(s: BodySections): string {
  return [
    '## Description',
    s.description,
    '',
    '---',
    '',
    '## Context',
    s.context,
    '',
    '## Client environment',
    s.environment,
    '',
    '## Active filters',
    s.filters,
    '',
    '## Heuristic classification (front)',
    s.classification,
    '',
    '## Recent console errors',
    s.consoleErrors,
    '',
    '## Recent failed requests',
    s.failedRequests,
    '',
    '---',
    s.footer,
  ].join('\n')
}

function renderSections(input: BuildIssueUrlInput): BodySections {
  const { context, classification } = input
  const description = input.description.trim() || '_(no description provided)_'

  return {
    description,
    context: [
      `- **URL**: ${context.browser.url}`,
      `- **Title**: ${context.shell.titleSlug}`,
      `- **Player**: ${context.shell.playerSlug ?? '_n/a_'}`,
      `- **Locale**: ${context.browser.locale}  ·  **Theme**: ${context.browser.theme}`,
      `- **Timestamp**: ${context.browser.timestampIso}`,
      `- **Focused element**: ${context.browser.focusedElement ?? '_n/a_'}`,
    ].join('\n'),
    environment: [
      `- **App version**: ${context.shell.appVersion ?? 'unknown'}`,
      `- **User-Agent**: ${context.browser.userAgent}`,
      `- **Viewport**: ${context.browser.viewportWidth} × ${context.browser.viewportHeight}`,
    ].join('\n'),
    filters: renderFilters(context.filters),
    classification: `- **Type**: ${classification.type}  ·  **Severity**: ${classification.severity}  ·  **Area**: ${classification.area}`,
    consoleErrors: renderConsoleErrors(context.console),
    failedRequests: renderFailedRequests(context.failedRequests),
    footer:
      '*Auto-generated by the feedback drawer — LevelUp web*\n' +
      '*An automatic analysis will be added as a comment in a few seconds.*',
  }
}

function renderFilters(filters: FeedbackContext['filters']): string {
  if (!filters) return '_(no active filter)_'
  const lines = [`- **Filter mode**: ${filters.filter_mode}`]
  if (filters.period?.start_date || filters.period?.end_date) {
    lines.push(
      `- **Period**: ${filters.period.start_date ?? '?'} → ${filters.period.end_date ?? '?'}`,
    )
  }
  if (filters.cascade?.modes?.length) {
    lines.push(`- **Modes**: ${filters.cascade.modes.join(', ')}`)
  }
  if (filters.cascade?.maps?.length) {
    lines.push(`- **Maps**: ${filters.cascade.maps.join(', ')}`)
  }
  if (filters.cascade?.playlists?.length) {
    lines.push(`- **Playlists**: ${filters.cascade.playlists.join(', ')}`)
  }
  if (filters.sessions?.picked_sessions?.length) {
    lines.push(`- **Sessions**: ${filters.sessions.picked_sessions.length} selected`)
  }
  return lines.length === 1 ? '_(default filters)_' : lines.join('\n')
}

function renderConsoleErrors(entries: FeedbackContext['console']): string {
  if (!entries.length) return '_(no console error captured)_'
  const lines = entries.map((e) => {
    const ts = formatTime(e.timestamp)
    const head = `[${e.level.toUpperCase()} ${ts}] ${e.message}`
    return e.stack ? `${head}\n${e.stack.split('\n').slice(0, 3).join('\n')}` : head
  })
  return '```js\n' + lines.join('\n') + '\n```'
}

function renderFailedRequests(reqs: FeedbackContext['failedRequests']): string {
  if (!reqs.length) return '_(no failed request captured)_'
  const lines = reqs.map((r) => `${r.method} ${r.url} → ${r.status} (${formatTime(r.timestamp)})`)
  return '```\n' + lines.join('\n') + '\n```'
}

function formatTime(ts: number): string {
  const d = new Date(ts)
  return d.toISOString().slice(11, 19)
}

// ---------------------------------------------------------------------------
// GitHub search helper (pour useSimilarIssues)
// ---------------------------------------------------------------------------

const SEARCH_RESERVED = /[:+"()/\\]/g

/**
 * Sanitize un titre user pour l'injecter dans `?q=` de la GitHub Search API.
 * Supprime les opérateurs réservés (`:`, `+`, `"`, `(`, `)`, `/`) qui casseraient
 * la query, puis collapse les espaces multiples.
 */
export function escapeSearchQuery(title: string): string {
  return title.replace(SEARCH_RESERVED, ' ').replace(/\s+/g, ' ').trim()
}

/**
 * Construit l'URL de la GitHub Search API pour les issues similaires.
 * Repo public → pas de token nécessaire. Limite 60 req/h/IP.
 */
export function buildSearchIssuesUrl(title: string): string {
  const sanitized = escapeSearchQuery(title)
  const q = `${sanitized} is:issue repo:${REPO}`
  return `https://api.github.com/search/issues?q=${encodeURIComponent(q)}&per_page=3`
}
